require("dotenv").config();
const express = require("express");
const cors = require("cors");
const { Pool } = require("pg");

const app = express();
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const PORT = process.env.PORT || 3000;
app.use(cors({ origin: process.env.CORS_ORIGIN || true }));
app.use(express.json({ limit: "1mb" }));

const points = (v = 0, e = 0, d = 0, g = 0, i = 0) => Number(v) * 3 + Number(e) + Number(d) + Number(g) * 2 - Number(i) * 2;
const slugify = value => String(value || "grupo").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "grupo";
const nextMonth = key => { const [year, month] = key.split("-").map(Number); return new Date(Date.UTC(year, month, 1)).toISOString().slice(0, 7); };

async function setup() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS grupos (id BIGSERIAL PRIMARY KEY, nome VARCHAR(120) NOT NULL, slug VARCHAR(70) UNIQUE NOT NULL, modalidade VARCHAR(60) NOT NULL DEFAULT 'Futebol', cidade VARCHAR(100), ativo BOOLEAN NOT NULL DEFAULT TRUE, criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS ciclos (id BIGSERIAL PRIMARY KEY, grupo_id BIGINT NOT NULL REFERENCES grupos(id) ON DELETE CASCADE, chave VARCHAR(7) NOT NULL, nome VARCHAR(80) NOT NULL, status VARCHAR(15) NOT NULL DEFAULT 'aberto' CHECK(status IN ('aberto','fechado')), aberta_em TIMESTAMPTZ NOT NULL DEFAULT NOW(), fechada_em TIMESTAMPTZ, UNIQUE(grupo_id, chave));
    CREATE TABLE IF NOT EXISTS atletas (id BIGSERIAL PRIMARY KEY, grupo_id BIGINT NOT NULL REFERENCES grupos(id) ON DELETE CASCADE, nome VARCHAR(120) NOT NULL, posicao VARCHAR(40), foto_url TEXT, ativo BOOLEAN NOT NULL DEFAULT TRUE, criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS desempenho_mensal (id BIGSERIAL PRIMARY KEY, grupo_id BIGINT NOT NULL REFERENCES grupos(id) ON DELETE CASCADE, ciclo_id BIGINT NOT NULL REFERENCES ciclos(id) ON DELETE CASCADE, atleta_id BIGINT NOT NULL REFERENCES atletas(id) ON DELETE CASCADE, pontos INTEGER NOT NULL DEFAULT 0, gols INTEGER NOT NULL DEFAULT 0, defesas INTEGER NOT NULL DEFAULT 0, vitorias INTEGER NOT NULL DEFAULT 0, empates INTEGER NOT NULL DEFAULT 0, infracoes INTEGER NOT NULL DEFAULT 0, atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(ciclo_id, atleta_id));
    CREATE INDEX IF NOT EXISTS idx_atletas_grupo ON atletas(grupo_id, ativo);
    CREATE INDEX IF NOT EXISTS idx_desempenho_ciclo ON desempenho_mensal(ciclo_id, pontos DESC);
  `);
  const demo = await pool.query("INSERT INTO grupos(nome,slug,modalidade) VALUES($1,$2,$3) ON CONFLICT(slug) DO UPDATE SET nome=EXCLUDED.nome RETURNING id", ["Sem Domínio", "sem-dominio", "Futebol"]);
  const groupId = demo.rows[0].id;
  const key = new Date().toISOString().slice(0, 7);
  await pool.query("INSERT INTO ciclos(grupo_id,chave,nome) VALUES($1,$2,$3) ON CONFLICT(grupo_id,chave) DO NOTHING", [groupId, key, `Ciclo ${key}`]);
}
async function currentCycle(groupId, client = pool) { const result = await client.query("SELECT * FROM ciclos WHERE grupo_id=$1 AND status='aberto' ORDER BY id DESC LIMIT 1", [groupId]); if (!result.rows[0]) throw new Error("Grupo sem ciclo aberto"); return result.rows[0]; }
async function group(req, res, next) { const result = await pool.query("SELECT * FROM grupos WHERE id=$1 AND ativo=true", [req.params.grupoId]); if (!result.rows[0]) return res.status(404).json({ error: "Grupo não encontrado" }); req.group = result.rows[0]; next(); }

app.get("/health", async (_req, res) => { try { await pool.query("SELECT 1"); res.json({ status: "ok", app: "FutPontos", database: "online" }); } catch { res.status(503).json({ status: "degraded", app: "FutPontos", database: "offline" }); } });
app.get("/grupos", async (_req, res) => res.json((await pool.query("SELECT id,nome,slug,modalidade,cidade FROM grupos WHERE ativo=true ORDER BY nome")).rows));
app.post("/grupos", async (req, res) => { const nome = String(req.body?.nome || "").trim(); if (!nome) return res.status(400).json({ error: "nome é obrigatório" }); try { const slug = slugify(req.body.slug || nome); const result = await pool.query("INSERT INTO grupos(nome,slug,modalidade,cidade) VALUES($1,$2,$3,$4) RETURNING *", [nome, slug, req.body.modalidade || "Futebol", req.body.cidade || null]); const g = result.rows[0]; const key = new Date().toISOString().slice(0, 7); await pool.query("INSERT INTO ciclos(grupo_id,chave,nome) VALUES($1,$2,$3)", [g.id, key, `Ciclo ${key}`]); res.status(201).json(g); } catch (error) { res.status(error.code === "23505" ? 409 : 500).json({ error: error.code === "23505" ? "slug já está em uso" : "Erro ao criar grupo" }); } });
app.get("/grupos/:grupoId", group, (req, res) => res.json(req.group));
app.get("/grupos/:grupoId/atletas", group, async (req, res) => { const result = await pool.query("SELECT * FROM atletas WHERE grupo_id=$1 AND ativo=true ORDER BY nome", [req.group.id]); res.json(result.rows); });
app.post("/grupos/:grupoId/atletas", group, async (req, res) => { const nome = String(req.body?.nome || "").trim(); if (!nome) return res.status(400).json({ error: "nome é obrigatório" }); const result = await pool.query("INSERT INTO atletas(grupo_id,nome,posicao,foto_url) VALUES($1,$2,$3,$4) RETURNING *", [req.group.id, nome, req.body.posicao || null, req.body.foto_url || null]); const ciclo = await currentCycle(req.group.id); await pool.query("INSERT INTO desempenho_mensal(grupo_id,ciclo_id,atleta_id) VALUES($1,$2,$3)", [req.group.id, ciclo.id, result.rows[0].id]); res.status(201).json(result.rows[0]); });
app.get("/grupos/:grupoId/ranking", group, async (req, res) => { const ciclo = await currentCycle(req.group.id); const result = await pool.query("SELECT a.id,a.nome,a.posicao,a.foto_url,d.pontos,d.gols,d.defesas,d.vitorias,d.empates,d.infracoes,$1::text AS ciclo FROM desempenho_mensal d JOIN atletas a ON a.id=d.atleta_id WHERE d.ciclo_id=$2 AND a.ativo=true ORDER BY d.pontos DESC,d.vitorias DESC,d.gols DESC,a.nome", [ciclo.nome, ciclo.id]); res.json({ grupo: req.group, ciclo, ranking: result.rows }); });
app.get("/grupos/:grupoId/ciclos", group, async (req, res) => res.json((await pool.query("SELECT c.*,COUNT(d.id)::int AS atletas FROM ciclos c LEFT JOIN desempenho_mensal d ON d.ciclo_id=c.id WHERE c.grupo_id=$1 GROUP BY c.id ORDER BY c.chave DESC", [req.group.id])).rows));
app.post("/grupos/:grupoId/desempenho", group, async (req, res) => { const atletaId = Number(req.body?.atleta_id); if (!Number.isInteger(atletaId)) return res.status(400).json({ error: "atleta_id é obrigatório" }); const ciclo = await currentCycle(req.group.id); const athlete = await pool.query("SELECT id FROM atletas WHERE id=$1 AND grupo_id=$2 AND ativo=true", [atletaId, req.group.id]); if (!athlete.rows[0]) return res.status(404).json({ error: "Atleta não encontrado neste grupo" }); const current = await pool.query("SELECT * FROM desempenho_mensal WHERE ciclo_id=$1 AND atleta_id=$2", [ciclo.id, atletaId]); const old = current.rows[0] || {}; const values = ["gols", "defesas", "vitorias", "empates", "infracoes"].map(key => Math.max(0, Number(old[key] || 0) + Number(req.body[key] || 0))); const [gols, defesas, vitorias, empates, infracoes] = values; const result = await pool.query("INSERT INTO desempenho_mensal(grupo_id,ciclo_id,atleta_id,gols,defesas,vitorias,empates,infracoes,pontos) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(ciclo_id,atleta_id) DO UPDATE SET gols=$4,defesas=$5,vitorias=$6,empates=$7,infracoes=$8,pontos=$9,atualizado_em=NOW() RETURNING *", [req.group.id,ciclo.id,atletaId,gols,defesas,vitorias,empates,infracoes,points(vitorias,empates,defesas,gols,infracoes)]); res.status(201).json(result.rows[0]); });
app.post("/grupos/:grupoId/ciclos/fechar", group, async (req, res) => { if (req.body?.confirm !== true) return res.status(400).json({ error: "Confirmação obrigatória" }); const client = await pool.connect(); try { await client.query("BEGIN"); const ciclo = await currentCycle(req.group.id, client); const ranking = await client.query("SELECT a.id,a.nome,d.pontos,d.gols,d.defesas,d.vitorias,d.empates,d.infracoes FROM desempenho_mensal d JOIN atletas a ON a.id=d.atleta_id WHERE d.ciclo_id=$1 ORDER BY d.pontos DESC,d.vitorias DESC,d.gols DESC", [ciclo.id]); await client.query("UPDATE ciclos SET status='fechado',fechada_em=NOW() WHERE id=$1", [ciclo.id]); const key = nextMonth(ciclo.chave); const novo = await client.query("INSERT INTO ciclos(grupo_id,chave,nome) VALUES($1,$2,$3) RETURNING *", [req.group.id,key,`Ciclo ${key}`]); await client.query("INSERT INTO desempenho_mensal(grupo_id,ciclo_id,atleta_id) SELECT $1,$2,id FROM atletas WHERE grupo_id=$1 AND ativo=true", [req.group.id,novo.rows[0].id]); await client.query("COMMIT"); res.status(201).json({ success:true, ciclo_fechado:ciclo, novo_ciclo:novo.rows[0], ranking_final:ranking.rows }); } catch(error) { await client.query("ROLLBACK"); res.status(500).json({ error:"Erro ao fechar ciclo", detalhes:error.message }); } finally { client.release(); } });

setup().then(() => app.listen(PORT, () => console.log(`FutPontos API na porta ${PORT}`))).catch(error => { console.error("Falha ao preparar API", error); process.exit(1); });
