const API = window.FUTPONTOS_API || "http://localhost:3000";
const $ = selector => document.querySelector(selector);
let groupId = null;
async function request(path, options) { const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json" }, ...options }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Erro na API"); return data; }
async function loadGroups() { const groups = await request("/grupos"); const select = $("#groupSelect"); select.innerHTML = groups.map(g => `<option value="${g.id}">${g.nome}</option>`).join(""); groupId = groups[0]?.id; if (groupId) await loadGroup(); select.onchange = async () => { groupId = select.value; await loadGroup(); }; }
async function loadGroup() { const data = await request(`/grupos/${groupId}/ranking`); $("#groupName").textContent = data.grupo.nome; $("#cycleName").textContent = data.ciclo.nome; $("#rankingCount").textContent = `${data.ranking.length} atletas`; $("#ranking").innerHTML = data.ranking.length ? data.ranking.map(a => `<li><div><span class="athlete-name">${escapeHtml(a.nome)}</span><span class="athlete-stats">⚽ ${a.gols} gols · 🧤 ${a.defesas} defesas · ${a.vitorias} vitórias</span></div><strong class="points">${a.pontos} pts</strong></li>`).join("") : "<li>Nenhum atleta cadastrado.</li>"; const athletes = await request(`/grupos/${groupId}/atletas`); $("#athlete").innerHTML = athletes.map(a => `<option value="${a.id}">${escapeHtml(a.nome)}</option>`).join(""); }
$("#performanceForm").addEventListener("submit", async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const body = { atleta_id:Number(form.get("atleta_id") || $("#athlete").value) }; ["gols","defesas","vitorias","empates","infracoes"].forEach(key => body[key] = Number(form.get(key) || 0)); try { await request(`/grupos/${groupId}/desempenho`, { method:"POST", body:JSON.stringify(body) }); $("#feedback").textContent = "Desempenho registrado."; event.currentTarget.reset(); await loadGroup(); } catch(error) { $("#feedback").textContent = error.message; } });
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char])); }
loadGroups().catch(error => { $("#groupName").textContent = "API indisponível"; $("#cycleName").textContent = error.message; });
